---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: temporal-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      enableServiceLinks: false
      containers:
        - name: ui
          image: temporalio/ui:latest
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend.temporal-system.svc.cluster.local:7233
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal-system
spec:
  selector:
    app: temporal-ui
  ports:
    - port: 8233
      targetPort: 8080
