---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-workers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  namespace: temporal-workers
spec:
  replicas: 0
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
        - name: worker
          image: python-temporal-worker:local
          imagePullPolicy: Never
          env:
            - name: TEMPORAL_HOST
              value: temporal-frontend.temporal-system.svc.cluster.local:7233
            - name: TEMPORAL_TASK_QUEUE
              value: data-pipeline
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
